quarkus:
  datasource:
    db-kind: postgresql
    devservices:
      volumes:
        "/tmp/test/data": /var/lib/postgresql/data
        "classpath:init.sql": /docker-entrypoint-initdb.d/init.sql
  hibernate-orm:
    database:
      generation: none
