quarkus:
  datasource:
    db-kind: postgresql
    devservices:
      volumes:
        "/tmp/test/data": /var/lib/postgresql/data
        "classpath:init.sql": /docker-entrypoint-initdb.d/init.sql
  hibernate-orm:
    database:
      generation: none

"%prod":
  quarkus:
    datasource:
      username: test
      password: test
      reactive:
        url: postgresql://localhost:5434/test
